version: '3'
services:
  frontend:
    build:
      context: /MỵJewelryAuction
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./JewelryAuction
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://myauction.c3kce2mquf6i.ap-southeast-1.rds.amazonaws.com:3306/myauction
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: huy141213
