version: '3'
services:
  frontend:
    image: node:alpine
    working_dir: /app
    build:
      context: ./frontend
      dockerfile: /MyJewelryAuction/Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - backend

  backend:
    image: openjdk:17-jdk-alpine
    working_dir: /app
    build:
      context: ./backend
      dockerfile: /MyJewelryAuction/JewelryAuction/Dockerfile
    ports:
      - "8080:8080"
    command: ["java", "-jar", "JewelryAuction-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://myauction.c3kce2mquf6i.ap-southeast-1.rds.amazonaws.com:3306/myauction
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: huy141213
